print("welcome to the offcial whitecaps Fan page")
print("lets sign a petition to change Whitecaps ultras name to 604 Ultras")
yes = input("say yes or no here")
trivia = input("now would you like to do a little trivia?")
print("Great!")
star = input("what star did the Whitecaps produce?")
print(" The road runner alphonso Daviess")
last = input("where did whitecaps get knocked out last season?")
print("2nd place")
